#!/bin/env bash

function subvol () {
	for su in $(btrfs su list /mnt | grep 'level 5' | awk '{print $9}'); do

		test -n "$su" || { echo "No subvolumes found"; exit 1; }

	    test "$su" = "root"      || test "${su}" = "@"          && mountAt="/"
	    test "$su" = "home"      || test "${su}" = "@home"      && mountAt="/home"
	    test "$su" = "cache"     || test "${su}" = "@cache"     && mountAt="/var/cache"
	    test "$su" = "log"       || test "${su}" = "@log"       && mountAt="/var/log"
	    test "$su" = "tmp"       || test "${su}" = "@tmp"       && mountAt="/tmp"
	    test "$su" = "snapshots" || test "${su}" = "@snapshots" && mountAt="/.snapshots"

	    echo "UUID=${getRootFS} $mountAt btrfs ${btrfsOptions},subvol=${su} 0 0"
	done
}

test "$(id -u)" -eq 0 || { echo "You must be root to run this script"; exit 1; }

btrfsOptions="ssd,noatime,space_cache=v2,compress=lzo"

getBootFS="$(lsblk -o uuid,fstype | grep 'vfat' | awk '{print $1}')"
getRootFS="$(lsblk -o uuid,fstype | grep 'btrfs' | awk '{print $1}')"
getSwapFS="$(lsblk -o uuid,fstype | grep 'swap' | awk '{print $1}')"

cat <<EOF > /mnt/etc/fstab
# /etc/fstab: static file system information.
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>

# EFI boot partition
UUID=${getBootFS} /boot/efi vfat defaults 0 1

# Mount btrfs subvolumes
$(subvol)

# Swap
UUID=${getSwapFS} none swap defaults 0 0
EOF

exit 0
