#!/bin/env bash

set -eo pipefail

# TODO: This needs to be ran in a loop to get the size of all child directories, not
# just the top level directories or the ones being checked here.

# Only the following directories are checked for size:
dirs=( "bin" "boot" "dev" "etc" "home" "lib" "lib64" "opt" "root" "sbin" "srv" "usr" "var" )

# Initialize total size in kilobytes
total_kb=0

echo "Individual directory sizes:"
for dir in "${dirs[@]}"; do
    test ! -d "${BUILD_DIR}/$dir" || {
        size_kb=$(du -s "${BUILD_DIR}/$dir" | cut -f1) ; total_kb=$((total_kb + size_kb))
    }
done

sed -i "s/Installed-Size:.*/Installed-Size: ${total_kb}/" "${BUILD_DIR}/DEBIAN/control"
