#!/bin/env bash

set -e

# shellcheck disable=SC2046
if test -d "../../mls" ; then

	test -d ../../mls/pool/main/b/"${PACKAGE}" || mkdir -vp ../../mls/pool/main/b/"${PACKAGE}"

    rm -vf ../../mls/pool/main/b/"${PACKAGE}"/*.deb
	dpkg-deb --root-owner-group --build "${PACKAGE_DIR}" \
		"../../mls/pool/main/b/${PACKAGE}/${PACKAGE}_${VERSION}_${ARCH}.deb"

else
	dpkg-deb --root-owner-group --build "${PACKAGE_DIR}" "${PACKAGE}_${VERSION}_${ARCH}.deb"
fi